### ISSUE TITLE
Windows platform relationships returns blank

### ISSUE THREAD

**Issue by verbeeksteven** [platformsh/platformsh-cli#1007]
Hello,

I am on Windows using PHP 7.4 windows with Windows Terminal and when I run `platform relationships` or anything needing relationship data such as sql or db:dump the relationships returns blank.

I turned on debug mode and all the commands seem fine, there is clearly relationships (as when I run it on my Mac it returns the correct data) and when I run `platform ssh` and then `echo $PLATFORM_RELATIONSHIPS` it shows the data.

Running the same command on MinGW (Git Bash) makes it work, so there must be something related to Windows Terminal causing it not to work?

Everything but the commands that require SSHing and dumping ENV variables seem to work.

What would be steps I should look at to diagnose the issue?

**Comment by pjcdawkins** [comment]
Rather a slow response sorry.

It might have been fixed by #1096

But if anyone still gets this problem - it sounds like something to do with SSH not opening a "login" shell, to diagnose, try as one command:

```
platform ssh 'echo $PLATFORM_RELATIONSHIPS'
```

if that returns empty, it points to the reason for the problem (I'm not sure of any solution yet, but it would be a start)
