### ISSUE TITLE
All commands should probably provide a non interactive mode

### ISSUE THREAD

**Issue by OriPekelman** [platformsh/platformsh-cli#103]
This would allow us to use the cli as a basis for other tools.

Login may be the exception here..? Will be easier to maintain then multiple client libs. We might also therfore have an option to output stuff that is easier to parse|pipe thinking for example about ide integration. . Do we really want to write that much java for phpstorm?

**Comment by pjcdawkins** [comment]
Closing because:
* The --yes and --no (-y and -n) options are in
* For all new commands, I've been making sure they can be used non-interactively
* 2.x has a --session-id option which makes non-interactive use a bit more sensible
* I'm not aware of any use cases yet apart from my own Jenkins scripts which I've been using for a while

Some commands may have specific limitations (such as `domain:add`) but I think those should be specific issues/PRs.
