### ISSUE TITLE
Handle 401 gracefully

### ISSUE THREAD

**Issue by ralt** [platformsh/platformsh-cli#285]
Getting this error is not very graceful:

```                                        
  [Guzzle\Http\Exception\ClientErrorResponseException]        
  Client error response                                       
  [status code] 401                                           
  [reason phrase] Unauthorized                                
  [url] https://marketplace.commerceguys.com/api/platform/me
```

Maybe a message could be shown saying "Have you tried `platform login`?".

**Comment by pjcdawkins** [comment]
Hm. The reason is that normal usage should never leave you in that situation, although you might be affected by the bug from 1 May (where new refresh tokens were not issued).

It is already somewhat graceful: login is triggered automatically if there is no access token or refresh token saved, and a 401 received for an access token triggers one automatic retry with a refresh token.

**Comment by pjcdawkins** [comment]
It still should never happen... but this is now handled in https://github.com/platformsh/platformsh-cli/commit/13b353604d9f184d4f96b83c5958ce96f3943934
