### ISSUE TITLE
Drush aliases broken in multi-app projects

### ISSUE THREAD

**Issue by jurgenhaas** [platformsh/platformsh-cli#342]
When updating the drush aliases with ```platform drush-aliases``` and if the project contains more than one app, then the aliases are brokwn.

For the local one, the doc-root should point to [PROJECT]/www/[APP-NAME]

For the remote one, the remote-user should be [PROJECT-ID]-master--[APP-NAME]

Any idea how we could preserve those changes until the pltform CLI is fixing this?

**Comment by pjcdawkins** [comment]
I don't think there is a workaround right now beyond copying the generated alias file and giving it another name.

One thing I could work on is how to get the doc root correct for the local alias.

For the remote alias, it's not possible to adapt to multi-app until we have implemented an API so that the CLI knows enough about what apps are on what remote environment (see #159, #326).

**Comment by pjcdawkins** [comment]
Improved in v2.7.0, although I notice there may still be an issue with the local alias.

**Comment by jurgenhaas** [comment]
This is great, I've just tested this and can confirm that the remote-user is set correctly as well as the root directory for the local alias. Excellent work!

@pjcdawkins what issue with the local alias are you referring to?

**Comment by pjcdawkins** [comment]
Ah, well thanks for testing! To be honest I forgot that I'd implemented the local alias fix too... I've just checked and it's there.
