### ISSUE TITLE
Include project name in default sql-dump filename

### ISSUE THREAD

**Issue by fuzzbomb** [platformsh/platformsh-cli#420]
Feature request.

Developers tend to accumulate lots of DB dumps, and share them around, too.

I think it would help to include the project name, so we get dumps like `acme-corporation_master-dump.sql`

**Comment by pjcdawkins** [comment]
I'd prefer the project ID rather than the project title - see my PR #423. This means the filename is going to uniquely identify that project, and the filename will be a reasonably predictable length and format (we can make a 'slug' of the project name but it won't be unique, and it will add complexity).

**Comment by pjcdawkins** [comment]
Added in [v2.13.0](https://github.com/platformsh/platformsh-cli/releases/tag/v2.13.0)
