### ISSUE TITLE
v2.13.3 - Drush aliases and web root

### ISSUE THREAD

**Issue by vincenzo** [platformsh/platformsh-cli#455]
Hi @pjcdawkins 

This relates to v2.13.3 (can't upgrade to 3.x yet). 

I've just upgrade from 2.13.0 to that and the build process has slightly changed, in that it now sets the web root to be a subfolder (in symlink form) of www, e.g. 

```
Build complete for application php
Web root: /home/vagrant/sites/ro/www/php
```

However, the drush aliases are still generated so that they have `/home/vagrant/sites/ro/www/` as web root, so drush commands won't work. 

Not sure if this is something you fixed in 3.x, but as I said, I can't upgrade to that yet :)

**Comment by pjcdawkins** [comment]
Hm, I think the build shouldn't have changed between patch versions like that. Or... it should only do that if you have multiple apps in your repository - but that logic has been there [since v2.7.0](https://github.com/platformsh/platformsh-cli/commit/991bf5fa7e6e0789575d3338532f082144dd16b2). Could I check out your repository perhaps? (give me a project ID at `patrick@platform.sh`)

**Comment by vincenzo** [comment]
It's a single Drupal app. 
It went back to normal when I reverted to 2.13.0. 

At the moment I can live with that. I'll work on upgrading to 3.x.
