### ISSUE TITLE
Feature request: Run original command after updating

### ISSUE THREAD

**Issue by rootwork** [platformsh/platformsh-cli#479]
Small request: When I run a platform command and it finds a new version, it will ask if I want to update. Fine.

But it would be nice if after updating, it _ran the original command I asked for_ instead of just updating and exiting.

A small thing, I know, but Platform CLI gets updated enough that I run into it enough for it to be a small annoyance.

**Comment by pjcdawkins** [comment]
Tricky, because of how it updates. If the Phar is replaced after PHP has opened it, and then you try to do something like load a class or internal file (as many commands do), PHP will instead load some completely different section of the Phar. Leads to very weird errors.

The other solution would be to replace the Phar at the end of execution, say, on a __destruct() call. That could be doable.

Meanwhile you could adjust the interval between automatic update checks (default is 24h) using `~/.PLATFORMSH/config.yaml`, or you could just say no to the prompt occasionally - it will remind you again the next day anyway.

**Comment by rootwork** [comment]
I think it's funny this was rejected, and then happened anyway with PR #529 :)

Anyway, thanks for making it happen! I appreciate it.

**Comment by pjcdawkins** [comment]
Sometimes arguing with me works :) thanks for noticing and closing the issue!
