### ISSUE TITLE
Drupal 8 projects using a composer flavor don't list Drupal cli commands

### ISSUE THREAD

**Issue by xtfer** [platformsh/platformsh-cli#493]
As described in the title, when `flavor: composer`, Drupal specific commands such as `drush-alias` are not available from `platform list` (though they still work fine).

**Comment by pjcdawkins** [comment]
The detection is not based on the `flavor`. The CLI looks for:

1. A file named `project.make*` or `drupal-org.make*`
2. A file named `index.php` containing the word `Drupal`
3. A `composer.json` JSON file which contains one of the `drupal/core` or `drupal/phing-drush-task` projects in the `requires` section

It does that in directories up to 2 levels deep inside the project  (so effectively `index.php`, `*/index.php`, `*/*/index.php`).

Source: https://github.com/platformsh/platformsh-cli/blob/cbcca5c01d02b33fdeacbdc69516a6260482d408/src/Local/Toolstack/Drupal.php#L17-L71

So, it's unclear what the problem is. Could you give more detail on the structure of the project?

**Comment by xtfer** [comment]
I used the setup wizard on project creation.

**Comment by xtfer** [comment]
Okay, I looked in the wrong place. This is working as expected. Thank you.

`local:drush-aliases (drush-aliases)        Find the project's Drush aliases`
