### ISSUE TITLE
curl installer missing php extension checks

### ISSUE THREAD

**Issue by ksjogo** [platformsh/platformsh-cli#495]
The curled install script (which I did not see in this repo, otherwise I would have pred) is missing the check for two dependencies/loaded php extensions:
```
// Check that the phar extension is installed (needed in this script).
check(
    'The "phar" PHP extension is installed.',
    'The "phar" PHP extension is required.',
    function () {
        return extension_loaded('phar');
    }
);
// Check that the phar extension is installed (needed in this script).
//transistive dependency caused by symfony/yaml, but they are not checking themselves
check(
    'The "ctype" PHP extension is installed.',
    'The "ctype" PHP extension is required.',
    function () {
        return extension_loaded('ctype');
    }
);
```

**Comment by pjcdawkins** [comment]
Thanks for the info - see https://github.com/platformsh/platformsh-cli/pull/496/commits/954b57ae (in PR #496)

To be consistent with the other extension warnings I downgraded missing `ctype` from a fatal error to a warning, because in theory you could still use the installer successfully, and then install `ctype` later before running `platform`.

**Comment by pjcdawkins** [comment]
The installer now checks for `phar` and warns about `ctype`: https://github.com/platformsh/platformsh-cli/commit/954b57ae775c0443e38c760b9992763150fce993
