### ISSUE TITLE
select a specific sql service name for platform sql:dump 

### ISSUE THREAD

**Issue by jbelhassan** [platformsh/platformsh-cli#548]
Hi,

Today we have to select a service by keypressing on 0 or 1 etc.
Is it possible to : 

$ platform sql:dump <sql_service_name>

Thanks

**Comment by jbelhassan** [comment]
for you info: 

$ platform db:dump 1

                                                     
  [RuntimeException]                                 
  Too many arguments, expected arguments "command".  
                                                     

Usage: platform db:dump [-f|--file FILE] [-t|--timestamp] [--stdout] [-p|--project PROJECT] [--host HOST] [-e|--environment ENVIRONMENT] [-A|--app APP]

For more information, type: platform help db:dump

**Comment by pjcdawkins** [comment]
I agree this would be very useful.

At the moment, this couldn't really be the _service_ name, because that's not available in an API or via SSH.

But we could do something with the _relationship_ name, maybe something like:

```
platform db:dump --relationship db1
```

And it should apply to all the `db` commands (`db:dump`, `db:size`, `db:sql`).

**Comment by pjcdawkins** [comment]
Selecting a `--relationship` is available in version 3.9.0
