### ISSUE TITLE
Allow cli flags to have default values via .platform/local/project.yaml

### ISSUE THREAD

**Issue by allgood2386** [platformsh/platformsh-cli#595]
I'd like to be able to set default flag values for certain commands. 
It would look something like the following:
```
command_defaults:
  db:
    dump:
      - FILE:"db/{DEFAULT_DUMP_NAME}"
```
//Results
```platform db:dump
      Saving database dump to ./<projectID>--<environmentID>--dump.sql
```

Also just fyi,
`{DEFAULT_DUMP_NAME}`
is made up.

I'm assuming there is a constant in there but I have not familiarized myself with the project enough to know what it is yet.

Consider the following use case:
I'm trying to set up zero config environments for our team. Docksal, a vm/container project, allows you to import a db from a directory on init. HOWEVER it MUST be in a directory (http://docksal.readthedocs.io/en/master/advanced/db-import/).

It would be nice to define a FILE flag, in platform, this makes it easier to create init scripts and update your local environment using some of the platform commands.

**Comment by pjcdawkins** [comment]
For that use case, you can now run:
```
mkdir -p db
platform db:dump --directory db --yes
```

Re. the feature request:

Defining those command arguments in a YAML file is [possible to implement](https://github.com/platformsh/platformsh-cli/compare/development...pjcdawkins:command-defaults)... but I think it will complicate users' understanding of a command too much.

The defaults would change depending on the current user and/or depending on the current directory. So you wouldn't be able to make any easy assumptions about the command defaults. That scares me.

It could possibly be OK via a kind of "Drush alias" system (see #233), because at least you'd have to explicitly pass the alias to the command (e.g. `platform @myproject db:dump`). So I'm going to close this issue, and maybe revisit #233 at some point.
