### ISSUE TITLE
drush commands using platform aliases fail env: drush: No such file or directory

### ISSUE THREAD

**Issue by markdorison** [platformsh/platformsh-cli#653]
Attempting to use the platform-created drush aliases results in an error:

```
$ drush [ALIAS.REDACTED] status
env: drush: No such file or directory
```

I attempted troubleshooting using the discussion in #626, but without success.

**Comment by finteractive** [comment]
I know this issue is long past but to save anyone else this pain here's the solution to this issue.

After a very long chain of back on forth comments with support the error reported is cause by the code base missing the required `.environment` file to allow drush to run on the remote server.

https://docs.platform.sh/frameworks/drupal8/drush.html#accessing-drush-within-the-project

Coping the `.environment` from the root in from the default [Drupal 8 template] to your project (https://github.com/platformsh/template-drupal8/) solved this for me.

**Comment by pjcdawkins** [comment]
Ahhh... so it was the _remote_ drush command that wasn't available in the PATH.

Thanks a lot for the solution @finteractive
