### ISSUE TITLE
Allow to use the command through non-localhost environment

### ISSUE THREAD

**Issue by shavounet** [platformsh/platformsh-cli#676]
I've tried to use the CLI with docker, but I couldn't use some commands like `platform login` due to the php server being binded to localhost : 
https://github.com/platformsh/platformsh-cli/blob/8f2669e4d17aaee9cce94b335562b496e1e87421/src/Command/Auth/BrowserLoginCommand.php#L65

Ideally, in this place (and maybe others), it should be configurable (through an ENV variable for example).

*Test case* : create a simple image (ubuntu with php, git, ssh, ...), install the CLI inside the image, and start a new container with the command `platform login` and correct port mapping. It should display normal output, but when going on http://localhost:5000/ the connection is marked as closed by remote.

*Workaround* : I use an API token, but I don't know if there is an other place where this might lead to issues

**Comment by pjcdawkins** [comment]
Security-wise, it absolutely needs to be on the local loopback interface (`127.0.0.1` rather than `localhost`), so that it doesn't cause requests over the network, and so that it can't be served by an external host (e.g. by a malicious attacker somehow taking over `localhost` via DNS).

The `platform auth:password-login` command is available for non-browser usage. That's also configurable as the default "login method", mentioned here: https://github.com/platformsh/platformsh-cli#customization

**Comment by pjcdawkins** [comment]
The presence of `auth:password-login` and this upcoming help message should resolve this issue:
https://github.com/platformsh/platformsh-cli/commit/8baebb450776fc9fed22867bed25d1bb9f0b0083
