### ISSUE TITLE
False positive warnings when installing in Platform.sh environment

### ISSUE THREAD

**Issue by yhoiseth** [platformsh/platformsh-cli#888]
We're installing the CLI as part of our build hook, as described [here](https://docs.platform.sh/development/cli/api-tokens.html#install-the-cli-on-a-platformsh-environment).

In the output when deploying, we're getting a lot of warnings (`W:`) which seems like they shouldn't be warnings:

```
      Executing build hook...
        Platform.sh CLI installer

        Environment check
          [*] The "json" PHP extension is installed.
          [*] The "phar" PHP extension is installed.
          [*] Git is installed.
          [*] The "openssl" PHP extension is installed.
          [*] The "pcre" PHP extension is installed.
          [!] The "curl" PHP extension is strongly recommended.
          [*] The "pcntl" and "posix" extensions are installed.
          [*] The "allow_url_fopen" setting is on.
          [*] The "apc.enable_cli" setting is off.

        Download
          Finding the latest version... done
          Downloading version 3.51.0... done
          Checking file integrity... done
          Checking that the file is a valid Phar... done

        Install
          Making the Phar executable... done
          Moving the Phar to your home directory... done
          Executable location: /app/.platformsh/bin/platform

        Running self:install command...

        W: Copying resource files... done
        W:
        W: Setting up autocompletion... skipped
        W:
        W: Selected shell configuration file: .environment
        W:
        W: Do you want to create the file automatically? [Y/n] y
        W:
        W: Configuration file created successfully: .environment
        W:
        W: To use the Platform.sh CLI, run:
        W:     source ~/.environment # (make sure your shell does this by default)
        W:     platform
```

**Comment by pjcdawkins** [comment]
`W:` doesn't really mean warning, it means "this came from the stderr pipe, not stdout"

stderr is used by this CLI, and others, for helpful/informational messages that are intended for humans to read (including but not limited to errors)

Normally in a shell you're able to treat these pipes differently by redirecting them. But the platform.sh git push deploy output doesn't have a way to distinguish stdout and stderr for the reader, except by this prefix... which I agree is misleading.

Additionally, the installer prints everything else to stdout because it just uses PHP's `printf()` ([here](https://github.com/platformsh/platformsh-cli/blob/development/dist/installer.php#L429)).

We could change the installer to redirect stderr to stdout purely for the self:install command (by adding `2>&1` [here](https://github.com/platformsh/platformsh-cli/blob/development/dist/installer.php#L283)).
