### ISSUE TITLE
cURL error 60 from missing CA bundle

### ISSUE THREAD

**Issue by DanielLindsay** [platformsh/platformsh-cli#990]
The CLI seems to be installed correctly but when I try to authenticate using `platform login`, after filling in my email and password in the browser, the command fails with the following errors:

[RequestException]
  cURL error 60: SSL certificate problem: unable to get local issuer certificate

and

[RingException]
  cURL error 60: SSL certificate problem: unable to get local issuer certificate

Environment:
- Windows 10 Enterprise, Version 1903
- PHP 7.3.2 (cli) (built: Feb  5 2019 22:55:35) ( ZTS MSVC15 (Visual C++ 2017) x64 )

**Comment by pjcdawkins** [comment]
Hi Daniel, does this answer help? https://stackoverflow.com/a/21114601

**Comment by nicolas-grekas** [comment]
Same on PHP 8. I have many users who have the same issue.

Disabling the curl extension makes think work for them. I guess that's because `fopen()` has better integration with system certificates.

A solution could be to not use curl on windows even if it is available. The platform cli doesn't need to use curl anyway.

**Comment by pjcdawkins** [comment]
Version 3.75.0 ^ may solve this: it includes `composer/ca-bundle`.
